#!/usr/bin/env bash
# 4-TCP_and_UDP_ports

# Display active Internet connections (only servers)
echo "Active Internet connections (only servers)"
sudo netstat -tulpn | grep -E "Proto|LISTEN"

# Display active UNIX domain sockets (only servers)
echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxpn | grep -E "Proto|LISTEN"
