#!/bin/bash
# 5-is_the_host_on_the_network

# Check if an argument (IP address) is provided
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the given IP 5 times
ping -c 5 "$1"
